import './index.css'

export const Showcase = () => (
	<div>
		<h1>Showcase</h1>
		<table>
			<thead>
				<tr>
					<th><h3>Name</h3></th>
					<th><h3>Visual</h3></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><h4>Link</h4></td>
					<td><a>Link</a></td>
				</tr>
				<tr>
					<td><h4>Button</h4></td>
					<td><button>Button</button></td>
				</tr>
				<tr>
					<td><h4>H1</h4></td>
					<td><h1>H1</h1></td>
				</tr>
				<tr>
					<td><h4>H2</h4></td>
					<td><h2>H2</h2></td>
				</tr>
				<tr>
					<td><h4>H3</h4></td>
					<td><h3>H3</h3></td>
				</tr>
				<tr>
					<td><h4>H4</h4></td>
					<td><h4>H4</h4></td>
				</tr>
				<tr>
					<td><h4>H5</h4></td>
					<td><h5>H5</h5></td>
				</tr>
				<tr>
					<td><h4>H6</h4></td>
					<td><h6>H6</h6></td>
				</tr>
				<tr>
					<td><p>paragraph</p></td>
					<td><p>paragraph</p></td>
				</tr>
			</tbody>
		</table>
	</div>
)
